### ISSUE TITLE
theme widget issue 

### ISSUE THREAD

**Issue by ciscohack** [samharju/tmux-synthweave-theme#1]
Thanks for the theme. Need help regarding the widget as it is not working. below is my config but I don't see CPU and ram usage also I tired empty widget that is also not working..please help

set -g @plugin 'samharju/tmux-synthweave-theme'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @synthweave_widgets 'C #{cpu_fg_color}#{cpu_percentage}#[default] M #{ram_fg_color}#{ram_percentage}#[default] #{sep}'
set -g @synthweave_copy_text "COPY"
set -g @synthweave_time_format "%T"

**Comment by samharju** [comment]
Can't access a workstation for a couple of days so can't test it, but I guess it's just the order of calls. Variables are picked when plugin is sourced, try moving @plugin calls last.

**Comment by ciscohack** [comment]
> Can't access a workstation for a couple of days so can't test it, but I guess it's just the order of calls. Variables are picked when plugin is sourced, try moving @plugin calls last.

You can take your time.. I tried that line moved initially and it didn't help though

**Comment by samharju** [comment]
I removed plugins from `~/tmux/plugins` and started with clean config:

.tmux.conf
```
set -g default-terminal "tmux-256color"
set -sa terminal-overrides ",xterm*:Tc"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'samharju/tmux-synthweave-theme'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @synthweave_widgets 'C #{cpu_fg_color}#{cpu_percentage}#[default] M #{ram_fg_color}#{ram_percentage}#[default] #{sep}'
set -g @synthweave_copy_text "COPY"
set -g @synthweave_time_format "%T"

run '~/.tmux/plugins/tpm/tpm'
```

I just installed plugins with `prefix + I` and it worked out of the gate. I'm using Ubuntu server 22.04.4.

**Comment by ciscohack** [comment]
@samharju Thanks a lot my friend for checking this... I am running macOS and ohmytmux and unfortunately this new config also not working for me. :(

**Comment by ciscohack** [comment]
> @samharju Thanks a lot my friend for checking this... I am running macOS and ohmytmux and unfortunately this new config also not working for me. :(

Thanks now I resolved there was one dup config in my Tmux causing a problem thanks once again.. one last help how can I change CPU foreground color to some random color just help me to know

**Comment by samharju** [comment]
You can customise those for tmux-cpu with variables, see [tmux-cpu docs](https://github.com/tmux-plugins/tmux-cpu?tab=readme-ov-file#customization)

Probably something like:

set -g @cpu_low_fg_color "#[fg=white]"

**Comment by ciscohack** [comment]
> You can customise those for tmux-cpu with variables, see [tmux-cpu docs](https://github.com/tmux-plugins/tmux-cpu?tab=readme-ov-file#customization)
> 
> Probably something like:
> 
> set -g @cpu_low_fg_color "#[fg=white]"

Thanks
